" All system-wide defaults are set in $VIMRUNTIME/archlinux.vim (usually just
" /usr/share/vim/vimfiles/archlinux.vim) and sourced by the call to :runtime
" you can find below.  If you wish to change any of those settings, you should
" do it in this file (/etc/vimrc), since archlinux.vim will be overwritten
" everytime an upgrade of the vim packages is performed.  It is recommended to
" make changes after sourcing archlinux.vim since it alters the value of the
" 'compatible' option.

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages.
runtime! archlinux.vim

" If you prefer the old-style vim functionalty, add 'runtime! vimrc_example.vim'
" Or better yet, read /usr/share/vim/vim80/vimrc_example.vim or the vim manual
" and configure vim to your own liking!

" do not load defaults if ~/.vimrc is missing
"let skip_defaults_vim=1


" Vim5 and later versions support syntax highlighting. Uncommenting the next
" line enables syntax highlighting by default.
if has("syntax")
  syntax on
endif

" Uncomment the following to have Vim jump to the last position when
" reopening a file
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

"EDITS
set termguicolors
colorscheme base16-tomorrow-night
set encoding=utf8
set number
set tabstop=4
set shiftwidth=4
set expandtab
filetype plugin indent on

"nerdTREE
map <C-N> :NERDTreeToggle<CR>
let NERDTreeQuitOnOpen = 1

"FZF
" Search and switch buffers
nmap <leader>b :Buffers<cr>
" " Find files by name under the current directory
nmap <leader>f :Files<cr>
" Find files by name under the home directory
 nmap <leader>h :Files ~/<cr>
